#!/usr/bin/env python2
#

import os
import sys
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("data_file",
                        help="Data file generated by Collector")
    parser.add_argument("-f", "--field", action='append',
                        help="Field to display, support simple arithmetic")
    parser.add_argument("-m", "--match", action='append',
                        help="Data record matcher, support shell wildcards")

    args = parser.parse_args()
    print args


if __name__ == "__main__":
    main()
