#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
#

'''
bentoo-merger.py - merge performance data from different sources

This tool merges collected performance data from different data sources. It
understands the internal structure of performance database and selects merge
keys automatically. Currently, it only supports data generated by Likwid
parser.
'''

import argparse
import sqlite3


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("ref_db",
                        help="Reference database")
    parser.add_argument("data_db",
                        help="Database to update from")
    parser.parse_args()


if __name__ == "__main__":
    main()
